name: 'smart_meter_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'smart_meter'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  smart_meter_analytics:
    # Staging models - raw data with minimal transformations
    staging:
      +materialized: view

    # Marts - business-oriented models
    marts:
      billing:
        +materialized: table
      grid:
        +materialized: table

# Tests
tests:
  +store_failures: true
